# Assignment 2:


#### 1.

In [1]:
import numpy as np
A = np.array([
    [2, -1],
    [0, 3]
])  
B = np.array([
    [1, 2],
    [-3, 4]
])
print("A+B:\n",A+B)
print("AB:\n",A@B)
print("3A-2B:\n",3*A - 2*B)


A+B:
 [[ 3  1]
 [-3  7]]
AB:
 [[ 5  0]
 [-9 12]]
3A-2B:
 [[ 4 -7]
 [ 6  1]]


#### 2.

In [2]:
print("Determinant of A:", np.linalg.det(A))
if(np.linalg.det(A) != 0):
    print("It is invertible!")
    A_1 = np.linalg.inv(A)
    print("Inverse of A:\n", A_1)


Determinant of A: 6.0
It is invertible!
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


#### 3.

In [3]:
C=np.array([
    [4,1],
    [-2,1]
    ])
eigenvalues, eigenvectors = np.linalg.eig(C)
for i in range(len(eigenvalues)):
    print(f"Eigenvalue {i+1}:", eigenvalues[i])
    print(f"Eigenvector {i+1}:", eigenvectors[:, i])

Eigenvalue 1: 3.0
Eigenvector 1: [ 0.70710678 -0.70710678]
Eigenvalue 2: 2.0
Eigenvector 2: [-0.4472136   0.89442719]


#### 4.

In [4]:

X= np.array([
    [4, 1.5, 100],
    [6, 2.0, 150]
])
y = np.array([20, 30])
Beta= np.linalg.pinv(X.T @ X) @ X.T @ y
print("For given dataset, regression coefficient(Beta) is:", Beta)
Test_Car= np.array([8, 3, 200])
Price_Predicted = Test_Car @ Beta
print("Predicted Price of Test Car:", Price_Predicted)

For given dataset, regression coefficient(Beta) is: [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01]
Predicted Price of Test Car: 39.99999999999998
